version: 2

updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "06:00"
          timezone: "Europe/Madrid"

      target-branch: "main"

      labels:
          - dependencies

      commit-message:
          prefix: "chore"
          include: "scope"

      open-pull-requests-limit: 5

      reviewers:
          - orangecatprog

      assignees:
          - orangecatprog

      groups:
          development-dependencies:
              dependency-type: "development"

          production-dependencies:
              dependency-type: "production"
